# Generated by Django 4.1.7 on 2023-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='sno',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
