# Generated by Django 4.1.7 on 2023-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_sno_usermodel_user_id_usermodel_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
