# Generated by Django 4.1.7 on 2023-04-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_usermodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-user_id']},
        ),
    ]
